# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

UpdateTheta_FCtemplateICAcpp <- function(template_mean, template_var, template_FC, G, prior_params, BOLD, Y_sq_sum, post_sums, sigma2_alpha, verbose) {
    .Call('_templateICAr_UpdateTheta_FCtemplateICAcpp', PACKAGE = 'templateICAr', template_mean, template_var, template_FC, G, prior_params, BOLD, Y_sq_sum, post_sums, sigma2_alpha, verbose)
}

Gibbs_AS_posteriorCPP <- function(nsamp, nburn, template_mean, template_var, S, A, G, tau_v, Y, alpha, final) {
    .Call('_templateICAr_Gibbs_AS_posteriorCPP', PACKAGE = 'templateICAr', nsamp, nburn, template_mean, template_var, S, A, G, tau_v, Y, alpha, final)
}

